############################################################
#
# updates for using https apt repo
#
############################################################
FROM opennetworklinux/builder8:1.8
MAINTAINER Wataru Ishida <ishida@nel-america.com>

RUN apt-get install -qy apt-transport-https
