name: ci

on:
    pull_request:
        branches:
        - master
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: crazy-max/ghaction-docker-buildx@v1
          with:
              version: latest
        - uses: actions/checkout@v2
        - run: git submodule update --init
        - run: make builder
        - run: make docker
