
###############################################################################
#
# Inclusive Makefile for the libonlp-arm64-wistron-wtp-01-c1-00 module.
#
# Autogenerated 2022-03-22 18:34:39.751422
#
###############################################################################
libonlp-arm64-wistron-wtp-01-c1-00_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

